# Generated by Django 3.2.4 on 2021-07-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0013_auto_20210625_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='notaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('concepto', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('neto', models.IntegerField(default=0)),
                ('iva_total', models.IntegerField(default=0)),
                ('total_v', models.IntegerField(default=0)),
                ('metodo_devolucion', models.CharField(default='DEFAULT VALUE', max_length=10)),
            ],
            options={
                'db_table': 'NotaDebito',
            },
        ),
        migrations.AlterField(
            model_name='boleta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='boletadetalle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='librodiario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
