# Generated by Django 3.1 on 2021-07-10 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0013_auto_20210625_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='notaDebito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('concepto', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('neto', models.IntegerField(default=0)),
                ('iva_total', models.IntegerField(default=0)),
                ('total_v', models.IntegerField(default=0)),
                ('metodo_devolucion', models.CharField(default='DEFAULT VALUE', max_length=10)),
                ('id_boleta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='apirest.boleta')),
            ],
            options={
                'db_table': 'NotaDebito',
            },
        ),
    ]
