# Generated by Django 3.2.4 on 2021-07-10 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0014_auto_20210709_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='notadebito',
            name='id_boleta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='apirest.boleta'),
        ),
    ]
