# Generated by Django 3.2.4 on 2021-07-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0016_alter_notadebito_id_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librodiario',
            name='debe',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='librodiario',
            name='haber',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
