# Generated by Django 3.2.4 on 2021-07-10 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0018_auto_20210710_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='notaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('concepto', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('neto', models.IntegerField(default=0)),
                ('iva_total', models.IntegerField(default=0)),
                ('total_v', models.IntegerField(default=0)),
                ('metodo_devolucion', models.CharField(default='1', max_length=10)),
                ('id_boleta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='apirest.boleta')),
            ],
            options={
                'db_table': 'NotaCredito',
            },
        ),
        migrations.DeleteModel(
            name='notaDebito',
        ),
    ]
